### PR TITLE
fix: getCAs and CRLs unsetting X509_CERT_DIR

### LINKED ISSUE #8501: [Bug]: Treatment of X509_CERT_DIR in BundleDeliveryClient
### Search before creating an issue

- [x] I have searched existing issues and confirmed this is not a duplicate

### Bug Description

The code currently in BundleDeliveryClient unsets `X509_CERT_DIR` just to define it immediately again.

This seems to be an error or at least an incomplete cleanup in this commit:
https://github.com/DIRACGrid/DIRAC/commit/dbd11ff91b77acc7c0ae2d44871d0134a18762f8#diff-4b559d033eb04c28a1bb49dc75edf5fe8f2ac4ed7ffbcc5bfe8269b8389170d0L152

In the original commit, the variable was unset, then the CAs were synced, then the variable was set again:
https://github.com/DIRACGrid/DIRAC/commit/b14870105ee123fe0beb2e11599bb1d9b3989482

### Steps to Reproduce

_No response_

### Expected Behavior

_No response_

### Actual Behavior

_No response_

### Environment

_No response_

### Relevant Log Output

```shell

```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by fstagni**
closes #8501 

BEGINRELEASENOTES

*Framework
FIX: getCAs and CRLs unsetting X509_CERT_DIR

ENDRELEASENOTES

### CODE REVIEW

**Review by maxnoe — APPROVED** [review]

**Comment by fstagni** [comment]
Probably needing https://github.com/DIRACGrid/management/pull/70

**Comment by chaen** [comment]
Just for my education: what's the point of unsetting the X509 variable ?

**Comment by fstagni** [comment]
> Just for my education: what's the point of unsetting the X509 variable ?

IIRC it's only for pilots, and for the case when a release is installed (not taken from CVMFS): not being "polluted" by an existing environment variable pointing to a possibly not-updated locations.

File: tests/CI/run_pilot.sh [hunk 1]
```diff
@@ -23,22 +23,27 @@ mkdir -p /home/dirac/etc/grid-security/vomsdir
...
+jq <pilot.json
 
-if command -v python &> /dev/null; then
+if command -v python &>/dev/null; then
   py='python'
-elif command -v python3 &> /dev/null; then
+elif command -v python3 &>/dev/null; then
   py='python3'
-elif command -v python2 &> /dev/null; then
+elif command -v python2 &>/dev/null; then
```
Comment (aldbr) [inline tests/CI/run_pilot.sh:46]: Fine here but for next PRs: can we avoid that kind of formatting changes unrelated with the PRs please?

File: tests/CI/docker-compose.yml [hunk 2]
```diff
@@ -308,7 +324,14 @@ services:
...
 
     healthcheck:
-      test: ["CMD", "/entrypoint.sh", "python", "-c", "import requests; requests.get('http://localhost:8000/.well-known/openid-configuration').raise_for_status()"]
+      test:
+        [
+          "CMD",
+          "/entrypoint.sh",
+          "python",
+          "-c",
+          "import requests; requests.get('http://localhost:8000/.well-known/openid-configuration').raise_for_status()",
```
Comment (aldbr) [inline tests/CI/docker-compose.yml:333]: Here for instance, it's taking me some time to figure out whether you changed that line or whether it's just a formatting change (I assume it's just formatting here).

**Review by aldbr — APPROVED** [review]

**Comment by chaen** [comment]
> > Just for my education: what's the point of unsetting the X509 variable ?
> 
> IIRC it's only for pilots, and for the case when a release is installed (not taken from CVMFS): not being "polluted" by an existing environment variable pointing to a possibly not-updated locations.

But aren't you updating a location that will never be used, given you set again the X509* ?

**Comment by fstagni** [comment]
The DIRAC's specific locations will always be looked up before the other ones, including those set by X509* variables.
